all:	FootNotePlugin.zip

FootNotePlugin_EXTRAS = lib/TWiki/Plugins/FootNotePlugin/Note.pm \
			lib/TWiki/Plugins/FootNotePlugin/LabelFormat.pm \
			pub/TWiki/FootNotePlugin/styles.css

include ../twikicfg.make

include ../plugin.make
