all:	InterwikiPreviewPlugin.zip

InterwikiPreviewPlugin_EXTRAS = lib/TWiki/Plugins/InterwikiPreviewPlugin/Rule.pm
InterwikiPreviewPlugin_EXTRAS += lib/TWiki/Plugins/InterwikiPreviewPlugin/Query.pm
InterwikiPreviewPlugin_EXTRAS += pub/TWiki/InterwikiPreviewPlugin/MochiKit.js
InterwikiPreviewPlugin_EXTRAS += pub/TWiki/InterwikiPreviewPlugin/query.js

InterwikiPreviewPlugin_EXTRA_PAGES = ${TWIKIPLUGINWEB}/InterWikiPreviews

include ../twikicfg.make

include ../plugin.make
