all:	InterwikiAjaxInfoPlugin.zip

InterwikiAjaxInfoPlugin_EXTRAS = lib/TWiki/Plugins/InterwikiAjaxInfoPlugin/Rule.pm
InterwikiAjaxInfoPlugin_EXTRAS += lib/TWiki/Plugins/InterwikiAjaxInfoPlugin/Query.pm
InterwikiAjaxInfoPlugin_EXTRAS += pub/TWiki/InterwikiAjaxInfoPlugin/query.js

include ../twikicfg.make

include ../plugin.make
